"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";

type Question = { id: string; exam: string; year: number | null; subject: string; topic: string | null; topicId?: string | null; topicOfficial?: boolean; difficulty?: number | null; prompt: string; options: unknown; correctAnswer: unknown; explanation: string | null; passage?: string | null; images?: string[] };
type TopicOption = { id: string; name: string; parentId: string | null; objective: string | null; subject?: string };
type Option = { id: string; text: string };
type ExamQuestion = Question & { options: Option[]; correctOption: string; optionOrder: string[] };
type SavedAttempt = { id: string; studentId: string; mode: "practice" | "full"; status: "active" | "submitted"; startedAt: number; durationSeconds: number; submittedAt?: number; subjects: string[]; questions: ExamQuestion[]; answers: Record<string, string>; marks: string[]; randomSeed: string; formFingerprint: string; count: number; practiceSeconds: number; currentQuestionId?: string; subjectPositions?: Record<string, string>; syncState?: "pending" | "synced" };

const SUBJECTS = ["Use of English", "Agricultural Science", "Arabic", "Art (Fine Art)", "Biology", "Chemistry", "Christian Religious Knowledge", "Commerce", "Computer Studies", "Economics", "French", "Geography", "Government", "Hausa", "History", "Home Economics", "Igbo", "Islamic Studies", "Literature in English", "Mathematics", "Music", "Physical Health Education", "Physics", "Principle of Accounts", "Yoruba"];
const FULL_COUNTS: Record<string, number> = { "Use of English": 60 };
const PRESETS = [5, 10, 20, 30, 40];
const DURATIONS = [5, 10, 15, 20, 30, 45, 60];
const DB_NAME = "tutor-me-cbt";

function openStore(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") return reject(new Error("Offline storage is unavailable in this browser."));
    const request = indexedDB.open(DB_NAME, 4);
    request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains("attempts")) db.createObjectStore("attempts", { keyPath: "id" }); if (!db.objectStoreNames.contains("content")) db.createObjectStore("content", { keyPath: "id" }); if (!db.objectStoreNames.contains("mistakes")) db.createObjectStore("mistakes", { keyPath: "questionId" }); if (!db.objectStoreNames.contains("studentMistakes")) db.createObjectStore("studentMistakes", { keyPath: "studentQuestionKey" }); if (!db.objectStoreNames.contains("identity")) db.createObjectStore("identity", { keyPath: "id" }); if (!db.objectStoreNames.contains("meta")) db.createObjectStore("meta", { keyPath: "id" }); if (!db.objectStoreNames.contains("syllabusTopics")) db.createObjectStore("syllabusTopics", { keyPath: "id" }); };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error("Could not open local CBT storage."));
  });
}
async function saveRecord<T>(storeName: string, value: T): Promise<void> { const db = await openStore(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(storeName, "readwrite"); tx.objectStore(storeName).put(value); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
async function readRecords<T>(storeName: string): Promise<T[]> { const db = await openStore(); const values = await new Promise<T[]>((resolve, reject) => { const req = db.transaction(storeName).objectStore(storeName).getAll(); req.onsuccess = () => resolve(req.result as T[]); req.onerror = () => reject(req.error); }); db.close(); return values; }
async function updateContentVersion(version: number): Promise<void> { const db = await openStore(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(["content", "meta", "syllabusTopics"], "readwrite"); const meta = tx.objectStore("meta"); const request = meta.get("JAMB"); request.onsuccess = () => { if (request.result?.version !== version) { tx.objectStore("content").clear(); tx.objectStore("syllabusTopics").clear(); meta.put({ id: "JAMB", version }); } }; tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
async function syncSavedAttempt(value: SavedAttempt): Promise<SavedAttempt | null> {
  const payload = { attemptId: value.id, idempotencyKey: value.id, mode: value.mode, startedAt: new Date(value.startedAt).toISOString(), durationSeconds: value.durationSeconds, submittedAt: new Date(value.submittedAt ?? Date.now()).toISOString(), subjects: value.subjects, randomSeed: value.randomSeed, questionOrder: value.questions.map((q) => q.id), optionOrder: Object.fromEntries(value.questions.map((q) => [q.id, q.optionOrder])), formFingerprint: value.formFingerprint, answers: value.answers, marks: value.marks, responses: value.questions.map((q) => ({ questionId: q.id, selectedAnswer: value.answers[q.id] ?? null })) };
  try { const response = await fetch("/api/cbt/questions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) return null; const updated = { ...value, syncState: "synced" as const }; await saveRecord("attempts", updated); return updated; } catch { return null; }
}
function stableShuffle<T>(items: T[], seed: string): T[] { const out = [...items]; let state = [...seed].reduce((n, c) => (n * 31 + c.charCodeAt(0)) >>> 0, 2166136261); for (let i = out.length - 1; i > 0; i--) { state = (Math.imul(state ^ (state >>> 16), 2246822519) + 3266489917) >>> 0; const j = state % (i + 1); [out[i], out[j]] = [out[j], out[i]]; } return out; }
function stratifiedSelection<T extends { topic: string | null; difficulty?: number | null; year: number | null }>(pool: T[], count: number, seed: string): T[] { const groups = new Map<string, T[]>(); for (const row of stableShuffle(pool, seed)) { const key = `${row.topic ?? "unclassified"}|${row.difficulty ?? "unrated"}|${row.year ?? "undated"}`; const list = groups.get(key) ?? []; list.push(row); groups.set(key, list); } const buckets = [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => stableShuffle(rows, `${seed}:${key}`)); const selected: T[] = []; while (selected.length < count) { let added = false; for (const bucket of buckets) { if (bucket.length && selected.length < count) { selected.push(bucket.pop()!); added = true; } } if (!added) break; } return selected; }
function optionRows(raw: unknown): Option[] { if (Array.isArray(raw)) return raw.map((o, i) => typeof o === "string" ? { id: String.fromCharCode(65 + i), text: o } : { id: String((o as { id?: string }).id ?? String.fromCharCode(65 + i)), text: String((o as { text?: string; value?: string }).text ?? (o as { value?: string }).value ?? "") }).filter((o) => o.text); if (raw && typeof raw === "object") return Object.entries(raw).map(([id, value]) => ({ id, text: String(value) })); return []; }
function answerId(answer: unknown, options: Option[]): string { if (typeof answer === "number") return options[answer]?.id ?? ""; if (typeof answer === "string") { const value = answer.trim(); return options.find((o) => o.id.toLowerCase() === value.toLowerCase())?.id ?? options.find((o) => o.text === value)?.id ?? ""; } if (answer && typeof answer === "object") { const v = answer as { id?: string; text?: string; value?: string }; return answerId(v.id ?? v.text ?? v.value, options); } return ""; }
function formatTime(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function topicLabel(topic: TopicOption, all: TopicOption[]) { const names = [topic.name]; let parent = topic.parentId ? all.find((item) => item.id === topic.parentId) : undefined; while (parent && names.length < 8) { names.unshift(parent.name); parent = parent.parentId ? all.find((item) => item.id === parent!.parentId) : undefined; } return names.join(" › "); }
function topicSubtreeIds(topicId: string, all: TopicOption[]) { const ids = new Set([topicId]); let changed = true; while (changed) { changed = false; for (const item of all) if (item.parentId && ids.has(item.parentId) && !ids.has(item.id)) { ids.add(item.id); changed = true; } } return ids; }
function randomId() { if (!globalThis.crypto?.randomUUID) throw new Error("Secure randomness is unavailable on this device."); return globalThis.crypto.randomUUID(); }

export function CbtExperience({ initialPractice }: { initialPractice?: { subject?: string; topic?: string; count: number } }) {
  const initialSubject = initialPractice?.subject && SUBJECTS.includes(initialPractice.subject) ? initialPractice.subject : "Biology";
  const [mode, setMode] = useState<"choose" | "practiceSetup" | "fullSetup" | "taking" | "results">(initialPractice ? "practiceSetup" : "choose");
  const [subject, setSubject] = useState(initialSubject);
  const [topic, setTopic] = useState(initialPractice?.topic ?? "");
  const [topics, setTopics] = useState<TopicOption[]>([]);
  const [questionCount, setQuestionCount] = useState(initialPractice?.count ?? 10);
  const [minutes, setMinutes] = useState(20);
  const [fullSubjects, setFullSubjects] = useState(["Biology", "Chemistry", "Physics"]);
  const [attempt, setAttempt] = useState<SavedAttempt | null>(null);
  const [activeQuestionId, setActiveQuestionId] = useState("");
  const [secondsLeft, setSecondsLeft] = useState(0);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [online, setOnline] = useState(true);
  const [confirmSubmit, setConfirmSubmit] = useState(false);
  const [cacheReady, setCacheReady] = useState(false);
  const [studentId, setStudentId] = useState<string | null>(null);
  const currentIndex = Math.max(0, attempt?.questions.findIndex((q) => q.id === activeQuestionId) ?? 0);
  const current = attempt?.questions[currentIndex];
  const answersCount = attempt ? Object.keys(attempt.answers).length : 0;
  const persist = useCallback(async (next: SavedAttempt) => { setAttempt(next); try { await saveRecord("attempts", next); } catch { setNotice("Could not save this answer on the device. Free storage space before continuing."); } }, []);

  useEffect(() => { queueMicrotask(() => setOnline(navigator.onLine)); const on = () => setOnline(true); const off = () => setOnline(false); window.addEventListener("online", on); window.addEventListener("offline", off); return () => { window.removeEventListener("online", on); window.removeEventListener("offline", off); }; }, []);
  useEffect(() => { if ("serviceWorker" in navigator) void navigator.serviceWorker.register("/cbt-sw.js").catch(() => setNotice("Offline app shell could not be prepared on this device.")); }, []);
  useEffect(() => { let live = true; const identity = async () => { try { const local = (await readRecords<{ id: string; studentId: string }>("identity")).find((row) => row.id === "currentStudent"); if (navigator.onLine) { const response = await fetch("/api/cbt/me", { cache: "no-store" }); const body = await response.json(); if (response.status === 401) { if (live) { setStudentId(null); setNotice(body.error ?? "Sign in to use CBT."); setCacheReady(true); } return; } if (response.ok && typeof body.studentId === "string") { await saveRecord("identity", { id: "currentStudent", studentId: body.studentId }); if (live) { if (local?.studentId !== body.studentId) { setAttempt(null); setMode("choose"); } setStudentId(body.studentId); } return; } } if (local && live) setStudentId(local.studentId); else if (live) { setNotice("Connect and sign in once to prepare this device for CBT."); setCacheReady(true); } } catch { const local = await readRecords<{ id: string; studentId: string }>("identity").catch(() => []); if (live && local[0]) setStudentId(local[0].studentId); else if (live) { setNotice("Connect and sign in once to prepare this device for CBT."); setCacheReady(true); } } }; void identity(); return () => { live = false; }; }, []);
  useEffect(() => { if (!studentId) return; let live = true; readRecords<SavedAttempt>("attempts").then((rows) => { if (!live) return; setCacheReady(true); const active = rows.filter((a) => a.studentId === studentId && a.status === "active").sort((a, b) => b.startedAt - a.startedAt)[0]; if (active) { setAttempt(active); setActiveQuestionId(active.currentQuestionId ?? active.questions[0]?.id ?? ""); setSecondsLeft(Math.max(0, Math.ceil((active.startedAt + active.durationSeconds * 1000 - Date.now()) / 1000))); setMode("taking"); } }).catch(() => { if (live) { setCacheReady(true); setNotice("Local CBT storage could not be opened. Check device storage and reload."); } }); return () => { live = false; }; }, [studentId]);
  useEffect(() => { const syncPending = () => { if (!navigator.onLine || !studentId) return; void readRecords<SavedAttempt>("attempts").then(async (rows) => { for (const saved of rows.filter((row) => row.studentId === studentId && row.status === "submitted" && row.syncState !== "synced")) await syncSavedAttempt(saved); }).catch(() => undefined); }; window.addEventListener("online", syncPending); syncPending(); return () => window.removeEventListener("online", syncPending); }, [studentId]);
  useEffect(() => { if (mode !== "practiceSetup" || !studentId) return; let live = true; fetch(`/api/cbt/questions?subject=${encodeURIComponent(subject)}&count=1&topics=1`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Syllabus topics unavailable."); return data; }).then(async (data) => { if (typeof data.contentVersion === "number") await updateContentVersion(data.contentVersion); const rows = Array.isArray(data.topics) ? data.topics.map((row: TopicOption) => ({ ...row, subject })) : []; for (const row of rows) await saveRecord("syllabusTopics", row); if (live) setTopics(rows); }).catch(async () => { const cache = await readRecords<TopicOption & { subject: string }>("syllabusTopics").catch(() => []); if (live) setTopics(cache.filter((row) => row.subject === subject)); }); return () => { live = false; }; }, [mode, subject, studentId]);
  async function startPractice() {
    if (!studentId) { setNotice("Sign in to start CBT and save your progress to your account."); return; }
    setBusy(true); setNotice("");
    try {
      let rows: Question[] = []; const poolSeed = randomId(); const seed = `${poolSeed}:${studentId}`;
      if (navigator.onLine) { try { const res = await fetch(`/api/cbt/questions?subject=${encodeURIComponent(subject)}&count=200&poolSeed=${poolSeed}${topic ? `&topicId=${encodeURIComponent(topic)}` : ""}`, { cache: "no-store" }); const data = await res.json(); if (res.status === 401) throw new Error(data.error ?? "Sign in to use CBT."); if (!res.ok) throw new Error(data.error ?? "Questions could not be loaded."); if (typeof data.contentVersion === "number") await updateContentVersion(data.contentVersion); rows = data.questions as Question[]; for (const q of rows) await saveRecord("content", { ...q, id: q.id }); } catch (error) { if (error instanceof Error && error.message.startsWith("Sign in")) throw error; const cachedQuestions = await readRecords<Question>("content"); const allowed = topic ? topicSubtreeIds(topic, topics) : null; const cached = cachedQuestions.filter((q) => q.subject === subject && (!allowed || (q.topicId && allowed.has(q.topicId)))); if (!cached.length) throw error; rows = cached; } }
      else { const cachedQuestions = await readRecords<Question>("content"); const allowed = topic ? topicSubtreeIds(topic, topics) : null; rows = cachedQuestions.filter((q) => q.subject === subject && (!allowed || (q.topicId && allowed.has(q.topicId)))); }
      const formatted = rows.map((q) => { const options = optionRows(q.options); const correctOption = answerId(q.correctAnswer, options); return { ...q, options, correctOption, optionOrder: options.map((o) => o.id) }; }).filter((q) => q.prompt && q.options.length >= 2 && q.correctOption);
      const topicName = topics.find((item) => item.id === topic); if (formatted.length < questionCount) throw new Error(`Only ${formatted.length} verified ${subject}${topicName ? ` · ${topicLabel(topicName, topics)}` : ""} questions are available on this device. ${questionCount} are required. No other topics or questions were substituted.`);
      const selected = stableShuffle(formatted, seed).slice(0, questionCount); const now = Date.now();
      const next: SavedAttempt = { id: randomId(), studentId, mode: "practice", status: "active", startedAt: now, durationSeconds: minutes * 60, subjects: [subject], questions: selected, answers: {}, marks: [], randomSeed: seed, formFingerprint: selected.map((q) => q.id).join("."), count: questionCount, practiceSeconds: minutes * 60, currentQuestionId: selected[0].id };
      if (new Set(selected.map((q) => q.id)).size !== selected.length) throw new Error("The available question pool contains duplicate IDs. This session was not started.");
      await persist(next); setActiveQuestionId(selected[0].id); setSecondsLeft(minutes * 60); setMode("taking");
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not start practice."); }
    finally { setBusy(false); }
  }
  async function startFull() {
    if (!studentId) { setNotice("Sign in to start CBT and save your progress to your account."); return; }
    if (fullSubjects.length !== 3 || fullSubjects.includes("Use of English")) { setNotice("Select three additional subjects. Use of English is included automatically."); return; }
    const selectedSubjects = ["Use of English", ...fullSubjects]; setBusy(true); setNotice("");
    try {
      let version: number | null = null; const poolSeed = randomId(); let pools: Array<readonly [string, Question[]]>;
      if (navigator.onLine) { try { pools = await Promise.all(selectedSubjects.map(async (s) => { const res = await fetch(`/api/cbt/questions?subject=${encodeURIComponent(s)}&count=180&poolSeed=${poolSeed}`, { cache: "no-store" }); const data = await res.json(); if (res.status === 401) throw new Error(`Sign in to use CBT. ${data.error ?? ""}`); if (!res.ok) throw new Error(data.error ?? "Question bank is unavailable."); if (typeof data.contentVersion === "number") version = data.contentVersion; return [s, data.questions as Question[]] as const; })); } catch (error) { if (error instanceof Error && error.message.startsWith("Sign in")) throw error; const cache = await readRecords<Question>("content"); pools = selectedSubjects.map((s) => [s, cache.filter((q) => q.subject === s)] as const); } }
      else { const cache = await readRecords<Question>("content"); pools = selectedSubjects.map((s) => [s, cache.filter((q) => q.subject === s)] as const); }
      if (version !== null) { await updateContentVersion(version); for (const [, pool] of pools) for (const question of pool) await saveRecord("content", { ...question, id: question.id }); }
      const previousForms = await readRecords<SavedAttempt>("attempts"); let seed = `${poolSeed}:${studentId}`; let result: ExamQuestion[] = []; let fingerprint = "";
      for (let formTry = 0; formTry < 3; formTry++) {
        if (formTry > 0) seed = `${randomId()}:${studentId}`; result = [];
        for (const [s, pool] of pools) {
          const required = FULL_COUNTS[s] ?? 40;
          const mapped = pool.map((q) => { const options = optionRows(q.options); const correctOption = answerId(q.correctAnswer, options); const shuffled = stableShuffle(options, `${seed}:${q.id}`); return { ...q, options: shuffled, correctOption, optionOrder: shuffled.map((o) => o.id) }; }).filter((q) => q.prompt && q.options.length === 4 && q.correctOption);
          if (mapped.length < required) throw new Error(`${s}: ${mapped.length} verified questions available; ${required} required. The full examination cannot start until the bank contains enough unique questions.`);
          result.push(...stratifiedSelection(mapped, required, `${seed}:${s}`));
        }
        if (result.length !== 180 || new Set(result.map((q) => q.id)).size !== 180) throw new Error("The proposed examination does not contain 180 unique question IDs. No attempt was started.");
        fingerprint = result.map((q) => `${q.id}:${q.optionOrder.join(",")}`).join("|");
        if (!previousForms.some((old) => old.studentId === studentId && old.formFingerprint === fingerprint)) break;
        if (formTry === 2) throw new Error("An exact prior form was detected. The system could not generate a distinct form from the available pool.");
      }
      const now = Date.now();
      const positions = Object.fromEntries(selectedSubjects.map((s) => [s, result.find((q) => q.subject === s)!.id]));
      const next: SavedAttempt = { id: randomId(), studentId, mode: "full", status: "active", startedAt: now, durationSeconds: 7200, subjects: selectedSubjects, questions: result, answers: {}, marks: [], randomSeed: seed, formFingerprint: fingerprint, count: 180, practiceSeconds: 7200, currentQuestionId: result[0].id, subjectPositions: positions };
      for (const q of result) await saveRecord("content", { ...q, id: q.id });
      await persist(next); setActiveQuestionId(result[0].id); setSecondsLeft(7200); setMode("taking");
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not start the full examination."); }
    finally { setBusy(false); }
  }
  const finishAttempt = useCallback(async (value: SavedAttempt) => {
    if (value.status === "submitted") return;
    const completed = { ...value, status: "submitted" as const, submittedAt: Date.now(), syncState: "pending" as const };
    await persist(completed); setAttempt(completed); setMode("results"); setConfirmSubmit(false);
    if (navigator.onLine) { const synced = await syncSavedAttempt(completed); if (synced) { setAttempt(synced); } else setNotice("This result is saved on this device and will sync when your account and connection are available."); }
    const missed = completed.questions.filter((q) => completed.answers[q.id] && completed.answers[q.id] !== q.correctOption);
    for (const q of missed) { const old = (await readRecords<{ studentQuestionKey: string; studentId: string; questionId: string; timesMissed: number; selectedAnswer: string | null; correctAnswer: string; subject: string; topic: string | null; firstSeen: number; lastSeen: number; attemptId: string }>("studentMistakes")).find((m) => m.studentId === completed.studentId && m.questionId === q.id); await saveRecord("studentMistakes", { studentQuestionKey: `${completed.studentId}:${q.id}`, studentId: completed.studentId, questionId: q.id, timesMissed: (old?.timesMissed ?? 0) + 1, selectedAnswer: completed.answers[q.id], correctAnswer: q.correctOption, subject: q.subject, topic: q.topic, firstSeen: old?.firstSeen ?? completed.startedAt, lastSeen: completed.submittedAt, attemptId: completed.id }); }
  }, [persist]);
  useEffect(() => { if (!attempt || mode !== "taking") return; const tick = () => { const left = Math.max(0, Math.ceil((attempt.startedAt + attempt.durationSeconds * 1000 - Date.now()) / 1000)); setSecondsLeft(left); if (left === 0) void finishAttempt(attempt); }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [attempt, mode, finishAttempt]);
  function setAnswer(value: string) { if (!attempt || attempt.status !== "active" || !current) return; void persist({ ...attempt, answers: { ...attempt.answers, [current.id]: value } }); }
  function jump(index: number) { if (!attempt?.questions[index]) return; const q = attempt.questions[index]; setActiveQuestionId(q.id); void persist({ ...attempt, currentQuestionId: q.id, subjectPositions: { ...attempt.subjectPositions, [q.subject]: q.id } }); }
  useEffect(() => { if (mode !== "taking") return; const keydown = (event: KeyboardEvent) => { if (!attempt) return; if (event.key === "ArrowRight") jump(Math.min(attempt.questions.length - 1, currentIndex + 1)); if (event.key === "ArrowLeft") jump(Math.max(0, currentIndex - 1)); if (/^[1-4]$/.test(event.key) && current) setAnswer(current.options[Number(event.key) - 1]?.id ?? ""); }; window.addEventListener("keydown", keydown); return () => window.removeEventListener("keydown", keydown); });

  if (mode === "taking" && attempt && current) {
    const subjectQuestions = attempt.questions.filter((q) => q.subject === current.subject); const subjectIndex = subjectQuestions.findIndex((q) => q.id === current.id) + 1;
    const stats = attempt.subjects.map((s) => { const qs = attempt.questions.filter((q) => q.subject === s); return { subject: s, count: qs.length, answered: qs.filter((q) => attempt.answers[q.id]).length, marked: qs.filter((q) => attempt.marks.includes(q.id)).length }; });
    return <main className={`cbt-app ${attempt.mode === "full" ? "cbt-exam-mode" : ""}`}><header className="cbt-topbar"><Link className="cbt-brand" href="/dashboard">TUTOR-ME</Link><strong>{attempt.mode === "full" ? "JAMB UTME Simulation" : "Practice CBT"}</strong><div className={`cbt-clock ${secondsLeft < 300 ? "clock-low" : ""}`} aria-label="Time remaining">◷ {formatTime(secondsLeft)}</div></header>{!online && <div className="cbt-offline-strip">Offline mode · your answers are saving on this device</div>}
      <nav className="cbt-subject-tabs" aria-label="Examination subjects">{attempt.subjects.map((s) => <button key={s} className={current.subject === s ? "selected" : ""} onClick={() => { const targetId = attempt.subjectPositions?.[s] ?? attempt.questions.find((item) => item.subject === s)?.id; const target = attempt.questions.findIndex((item) => item.id === targetId); if (target >= 0) jump(target); }}>{s.toUpperCase()}</button>)}</nav>
      <div className="cbt-session-layout"><section className="cbt-question-pane"><div className="cbt-question-heading"><span>{current.subject}{current.topic ? ` · ${current.topic}` : ""}</span><b>Question {attempt.mode === "full" ? subjectIndex : currentIndex + 1} / {attempt.mode === "full" ? subjectQuestions.length : attempt.count}</b></div>{current.passage && <aside className="cbt-passage"><strong>Passage</strong><p>{current.passage}</p></aside>}<p className="cbt-prompt">{current.prompt}</p><div className="cbt-options">{current.options.map((option, index) => <button key={option.id} className={attempt.answers[current.id] === option.id ? "picked" : ""} onClick={() => setAnswer(option.id)} aria-pressed={attempt.answers[current.id] === option.id}><span>{String.fromCharCode(65 + index)}</span><i>{option.text}</i>{attempt.answers[current.id] === option.id && <b>✓</b>}</button>)}</div><button className={`cbt-mark ${attempt.marks.includes(current.id) ? "marked" : ""}`} onClick={() => void persist({ ...attempt, marks: attempt.marks.includes(current.id) ? attempt.marks.filter((id) => id !== current.id) : [...attempt.marks, current.id] })}>{attempt.marks.includes(current.id) ? "★ Marked for review" : "☆ Mark for review"}</button><div className="cbt-control-row"><button onClick={() => jump(Math.max(0, currentIndex - 1))} disabled={!currentIndex}>← Back</button><button className="cbt-next" onClick={() => jump(Math.min(attempt.questions.length - 1, currentIndex + 1))} disabled={currentIndex === attempt.questions.length - 1}>Next →</button></div><div className="cbt-submit-line"><span>{answersCount} answered · {attempt.questions.length - answersCount} unanswered</span><button onClick={() => setConfirmSubmit(true)}>Submit examination</button></div></section>
      {attempt.mode === "practice" && attempt.answers[current.id] && <div className={`cbt-feedback ${attempt.answers[current.id] === current.correctOption ? "correct" : "incorrect"}`} role="status"><strong>{attempt.answers[current.id] === current.correctOption ? "Correct" : "Incorrect"}</strong><span>Your answer: {current.options.find((o) => o.id === attempt.answers[current.id])?.text}</span>{attempt.answers[current.id] !== current.correctOption && <span>Correct answer: {current.options.find((o) => o.id === current.correctOption)?.text}</span>}{current.explanation && <p>{current.explanation}</p>}</div>}
      <aside className="cbt-palette"><div className="cbt-palette-head"><strong>Go to question</strong><span>{attempt.marks.length} marked</span></div><div className="cbt-key" aria-label="Question palette">{attempt.questions.map((q, i) => <button key={q.id} aria-label={`Question ${i + 1}${attempt.answers[q.id] ? ", answered" : ", unanswered"}${attempt.marks.includes(q.id) ? ", marked" : ""}`} title={`${q.subject} · ${i + 1}`} className={`${q.id === current.id ? "now " : ""}${attempt.answers[q.id] ? "answered " : ""}${attempt.marks.includes(q.id) ? "marked " : ""}`} onClick={() => jump(i)}>{i + 1}</button>)}</div><div className="cbt-subject-summary">{stats.map((s) => <div key={s.subject}><span>{s.subject}</span><b>{s.answered}/{s.count}</b></div>)}</div><div className="cbt-legend"><span><i className="now"/>Current</span><span><i className="answered"/>Answered</span><span><i className="marked"/>Marked</span><span><i/>Unanswered</span></div>{attempt.mode === "full" && <p className="cbt-no-feedback">Answers and explanations are held until submission.</p>}</aside></div>
      {confirmSubmit && <div className="cbt-overlay"><section role="dialog" aria-modal="true" aria-labelledby="submit-title"><h2 id="submit-title">Review before submission</h2>{stats.map((s) => <p key={s.subject}>{s.subject}: <b>{s.answered}/{s.count}</b> answered · {s.marked} marked</p>)}<p>Total answered: <b>{answersCount}/{attempt.questions.length}</b></p><div><button onClick={() => setConfirmSubmit(false)}>Return to examination</button><button className="cbt-next" onClick={() => void finishAttempt(attempt)}>Confirm submission</button></div></section></div>}</main>;
  }
  if (mode === "results" && attempt) {
    const correct = attempt.questions.filter((q) => attempt.answers[q.id] === q.correctOption).length; const incorrect = Object.keys(attempt.answers).length - correct; const accuracy = answersCount ? Math.round(correct / answersCount * 100) : 0; const topicSummary = [...new Set(attempt.questions.map((q) => q.topic).filter((name): name is string => !!name))].map((name) => { const questions = attempt.questions.filter((q) => q.topic === name && attempt.answers[q.id]); const hits = questions.filter((q) => attempt.answers[q.id] === q.correctOption).length; return { name, answered: questions.length, accuracy: questions.length ? Math.round(hits / questions.length * 100) : 0 }; }).filter((topic) => topic.answered > 0);
    return <main className="cbt-app"><header className="cbt-topbar"><Link className="cbt-brand" href="/dashboard">TUTOR-ME</Link><strong>{attempt.mode === "full" ? "JAMB UTME Simulation · Results" : "Practice results"}<small> TUTOR-ME practice accuracy · not an official examination score</small></strong></header><section className="cbt-results-view"><h1>Session complete</h1><div className="cbt-result-summary"><div><b>{correct}/{attempt.questions.length}</b><span>Correct</span></div><div><b>{incorrect}</b><span>Incorrect</span></div><div><b>{attempt.questions.length - answersCount}</b><span>Unanswered</span></div><div><b>{accuracy}%</b><span>Accuracy</span></div><div><b>{formatTime(Math.max(0, Math.min(attempt.durationSeconds, Math.floor(((attempt.submittedAt ?? attempt.startedAt) - attempt.startedAt) / 1000))))}</b><span>Time used</span></div></div>{attempt.subjects.map((s) => { const qs = attempt.questions.filter((q) => q.subject === s); const n = qs.filter((q) => attempt.answers[q.id] === q.correctOption).length; const wrong = qs.filter((q) => attempt.answers[q.id] && attempt.answers[q.id] !== q.correctOption).length; return <div className="cbt-result-subject" key={s}><b>{s}</b><span>{n} correct · {wrong} incorrect · {qs.length - n - wrong} unanswered · {qs.length ? Math.round(n / qs.length * 100) : 0}%</span></div>; })}<h2>Topic performance</h2>{topicSummary.length ? topicSummary.map((topic) => <div className="cbt-result-subject" key={topic.name}><b>{topic.name}</b><span>{topic.accuracy}% from {topic.answered} answered · {topic.accuracy >= 80 ? "Strong topic" : topic.accuracy < 60 ? "Topic to review" : "In progress"}</span></div>) : <p>No mapped topic performance is available for this attempt.</p>}<h2>Review answers</h2>{attempt.questions.map((q, i) => <article className="cbt-review-answer" key={q.id}><strong>{q.subject} · {q.topic ?? "Unclassified topic"} · Question {i + 1}</strong><p>{q.prompt}</p><p>Your answer: {q.options.find((o) => o.id === attempt.answers[q.id])?.text ?? "Not answered"}</p><p>Correct answer: {q.options.find((o) => o.id === q.correctOption)?.text}</p>{q.explanation && <small>{q.explanation}</small>}</article>)}<button className="cbt-next" onClick={() => { setAttempt(null); setMode("choose"); }}>Return to CBT</button></section></main>;
  }
  return <main className="cbt-app cbt-setup"><header className="cbt-topbar"><Link className="cbt-brand" href="/dashboard">TUTOR-ME</Link><strong>Computer Based Testing</strong><span>{online ? "Connected" : "Offline"}</span></header><section className="cbt-setup-content"><div><span className="cbt-kicker">FOCUSED EXAM PRACTICE</span><h1>Choose your examination.</h1><p>Use questions available in the TUTOR-ME question bank. Your answers and active attempt are saved on this device.</p></div>{notice && <div className="cbt-notice" role="status">{notice}</div>}{mode === "choose" && <div className="cbt-mode-cards"><button onClick={() => { setNotice(""); setMode("practiceSetup"); }}><span>01</span><strong>Practice CBT</strong><small>Select a subject, optional mapped topic, question count and flexible time.</small><b>Set up practice →</b></button><button onClick={() => { setNotice(""); setMode("fullSetup"); }}><span>02</span><strong>Full JAMB Simulation</strong><small>Four subjects · 180 questions · fixed two-hour examination.</small><b>Choose subjects →</b></button></div>}
    {mode === "practiceSetup" && <section className="cbt-setup-card"><h2>Practice setup</h2><label>Subject<select value={subject} onChange={(e) => { setSubject(e.target.value); setTopic(""); }}>{SUBJECTS.map((s) => <option key={s}>{s}</option>)}</select></label><label>Topic <span>Optional · mapped syllabus topics only</span><select value={topic} onChange={(e) => setTopic(e.target.value)}><option value="">Any verified topic</option>{topics.map((t) => <option key={t.id} value={t.id}>{topicLabel(t, topics)}</option>)}</select></label><div className="cbt-range-head"><label htmlFor="question-count">Questions</label><b>{questionCount}</b></div><input id="question-count" type="range" min="1" max="40" value={questionCount} onChange={(e) => setQuestionCount(Number(e.target.value))}/><div className="cbt-presets">{PRESETS.map((n) => <button className={n === questionCount ? "active" : ""} key={n} onClick={() => setQuestionCount(n)}>{n}</button>)}</div><fieldset><legend>Practice time</legend><div className="cbt-presets">{DURATIONS.map((n) => <button className={n === minutes ? "active" : ""} key={n} onClick={() => setMinutes(n)}>{n} min</button>)}</div></fieldset><button className="cbt-next cbt-start" disabled={busy || !cacheReady} onClick={() => void startPractice()}>{busy ? "Preparing questions…" : "Start practice"}</button></section>}
    {mode === "fullSetup" && <section className="cbt-setup-card"><h2>Select your four subjects</h2><p>Use of English is included automatically. Select three additional subjects for this simulation.</p><div className="cbt-subject-select">{SUBJECTS.filter((s) => s !== "Use of English").map((s) => <label key={s}><input type="checkbox" checked={fullSubjects.includes(s)} onChange={(e) => setFullSubjects((old) => e.target.checked ? [...old, s] : old.filter((x) => x !== s))}/>{s}</label>)}</div><div className="cbt-fixed-time"><span>Questions</span><b>60 + 40 + 40 + 40 = 180</b><span>Time</span><b>02:00:00 · Fixed</b></div><button className="cbt-next cbt-start" disabled={busy} onClick={() => void startFull()}>{busy ? "Checking question availability…" : "Start full examination"}</button></section>}
    {mode !== "choose" && <button className="cbt-back-link" onClick={() => { setMode("choose"); setNotice(""); }}>← Back to examination choices</button>}<p className="cbt-honesty">Questions must be sourced, rights-cleared and verified before they enter an examination. TUTOR-ME is independent and is not affiliated with or endorsed by JAMB.</p></section></main>;
}
