"use client";

import { useState } from "react";
import Link from "next/link";

const guides = [
  { category: "Study tips", tag: "STUDY GUIDE", title: "Turn a long syllabus into a weekly plan", summary: "Break a broad subject into smaller topics, then leave room in your week to retry questions you found difficult.", read: "4 min read", body: ["Start by listing the topics you need to cover. Use the current syllabus for your exam, then divide the list into short weekly groups.", "Give each topic a first session for learning and a second session for retrieval practice. Space the sessions apart so you have to recall what you learned.", "Keep one flexible session each week for questions you missed. Your plan should make it easy to adjust when school or home responsibilities change."] },
  { category: "JAMB", tag: "EXAM PREPARATION GUIDE", title: "Use the question stem before choosing an answer", summary: "A careful first read helps you spot what a question is asking, especially when the answer options look similar.", read: "3 min read", body: ["Read the whole question before looking at the options. Notice words such as ‘most likely’, ‘except’ and ‘nearest in meaning’.", "Try to answer in your own words before checking the options. This can help you compare each option against the question rather than choosing a familiar phrase.", "After checking the explanation, record the topic if the answer surprised you. Revisit the topic later instead of repeating the same question straight away."] },
  { category: "WAEC", tag: "EXAM PREPARATION GUIDE", title: "Practise writing clear steps in a calculation", summary: "Showing a method gives you a chance to check your thinking, not just the final answer.", read: "4 min read", body: ["Write down the information given and the quantity the question asks you to find.", "Choose a formula or method and show each substitution clearly. Keep units beside your values where they apply.", "Check whether the final answer makes sense in size and units. Use the marking guidance for your specific exam when available."] },
  { category: "NECO", tag: "EXAM PREPARATION GUIDE", title: "Build a useful revision checklist", summary: "A short checklist helps you return to topics and see what still needs practice.", read: "3 min read", body: ["Group the topics by subject and mark each as not started, learning or ready to practise.", "Keep the checklist close to your study plan. Update it after a lesson and after you have attempted questions.", "A topic can move back to ‘learning’ when practice shows a gap. That is useful feedback, not a setback."] },
  { category: "Admissions", tag: "ADMISSION GUIDE", title: "Check course requirements before setting your target", summary: "Course and institution requirements can vary. Confirm the current entry information before relying on a subject combination.", read: "5 min read", body: ["Write down the programme and institution you are considering. Similar course names can have different requirements.", "Use the current JAMB Integrated Brochure and Syllabus System (IBASS) to check programme eligibility and UTME subject combinations.", "Confirm any additional requirements with the institution and for the correct admission year. Keep a note of the source and when you checked it."] },
  { category: "Scholarships", tag: "OPPORTUNITY CHECKLIST", title: "Check a scholarship offer before sharing your details", summary: "Use a few simple checks to understand who is offering an opportunity and what information an application asks for.", read: "3 min read", body: ["Find the opportunity on the provider’s own website and confirm the organisation name, eligibility and closing date.", "Read the privacy notice before sending documents. Be careful if an application asks for unexpected fees or sensitive information through an unofficial contact.", "Save the provider page and the deadline so you can check for changes before submitting."] },
  { category: "School updates", tag: "STUDENT CHECKLIST", title: "Keep your study routine realistic during a busy week", summary: "When schoolwork increases, a shorter focused session can help you keep a study habit without overloading your day.", read: "3 min read", body: ["Choose one subject and one small task, such as revising a definition or attempting five questions.", "Set a clear stopping point and leave a note about what to continue next time.", "Move unfinished tasks in your plan rather than trying to fit everything into one evening."] },
];

const categories = ["All", "JAMB", "WAEC", "NECO", "Admissions", "Scholarships", "Study tips", "School updates"];

export function ResourcesDirectory({ mode }: { mode: "news" | "admission" | "scholarships" }) {
  if (mode === "admission") return <AdmissionGuide/>;
  if (mode === "scholarships") return <ScholarshipDirectory/>;
  return <EducationDesk/>;
}

function EducationDesk() {
  const [category, setCategory] = useState("All");
  const [story, setStory] = useState<(typeof guides)[number] | null>(null);
  const visible = category === "All" ? guides : guides.filter((item) => item.category === category);
  return <section className="resource-workspace"><div className="resource-page-heading"><div><span className="eyebrow">TUTOR-ME EDUCATION DESK</span><h2>Study guides and useful updates.</h2><p>Practical learning advice, admissions reminders and careful signposts to official information.</p></div><span className="local-badge">EDITORIAL PREVIEW · NO LIVE ANNOUNCEMENTS</span></div><div className="resource-categories" role="tablist" aria-label="Education desk categories">{categories.map((item) => <button type="button" role="tab" aria-selected={category === item} className={category === item ? "resource-category-active" : ""} key={item} onClick={() => { setCategory(item); setStory(null); }}>{item}</button>)}</div>{story ? <article className="resource-article"><button type="button" className="resource-back" onClick={() => setStory(null)}>← &nbsp;Back to guides</button><span className="resource-story-tag">{story.tag} · TUTOR-ME</span><h3>{story.title}</h3><p className="resource-story-summary">{story.summary}</p><div className="resource-story-body">{story.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="resource-story-note">This is general study guidance, not an official exam announcement. Check the exam body or institution for current requirements and dates.</div><Link href={story.category === "Admissions" ? "/admission" : story.category === "Scholarships" ? "/scholarships" : "/learn"} className="text-link">{story.category === "Admissions" ? "Explore admission guidance" : story.category === "Scholarships" ? "View opportunity checklist" : "Continue learning"} ↗</Link></article> : <>{visible.length === 0 ? <div className="resource-empty"><span>⌕</span><h3>No guides in this category yet.</h3><p>Choose another category to explore study advice and preparation guides.</p></div> : <div className="resource-story-grid">{visible.map((item) => <article className="resource-story-card" key={item.title}><span className="resource-story-tag">{item.tag}</span><small>{item.category} · {item.read}</small><h3>{item.title}</h3><p>{item.summary}</p><button type="button" onClick={() => setStory(item)}>Read guide <span>→</span></button></article>)}</div>}<p className="resource-editorial-note">TUTOR-ME guides are editorial study resources. We do not publish unverified exam-body announcements here.</p></>}</section>;
}

function AdmissionGuide() {
  const [courseArea, setCourseArea] = useState("Science and technology");
  const [institution, setInstitution] = useState("");
  const [checked, setChecked] = useState(false);
  return <section className="resource-workspace"><div className="resource-page-heading"><div><span className="eyebrow">COURSE & ADMISSION GUIDANCE</span><h2>Check the official requirements for your next step.</h2><p>Course eligibility and subject combinations vary by programme, institution and admission year.</p></div><span className="local-badge">GUIDANCE TOOL PREVIEW</span></div><div className="admission-guide-grid"><article className="admission-checker-card"><span className="eyebrow">START A COURSE CHECK</span><h3>What are you considering?</h3><p>Use these choices to prepare your checklist. This screen does not determine eligibility.</p><label htmlFor="course-area">Course area</label><select id="course-area" value={courseArea} onChange={(event) => setCourseArea(event.target.value)}><option>Science and technology</option><option>Health and life sciences</option><option>Arts and humanities</option><option>Business and social sciences</option><option>Education</option></select><label htmlFor="institution-name">Institution you’re considering</label><input id="institution-name" value={institution} onChange={(event) => setInstitution(event.target.value)} placeholder="Type an institution name"/><button type="button" className="button" onClick={() => setChecked(true)}>Prepare my checklist <span>→</span></button>{checked && <div className="admission-check-result"><b>Before you decide{institution ? ` on ${institution}` : " on a programme"}:</b><ol><li>Search your intended programme in the current JAMB IBASS brochure.</li><li>Confirm the UTME subjects and O’Level requirements for the institution.</li><li>Check the institution’s own page for the current admission year.</li></ol><small>Selected area: {courseArea}. This is a checklist, not an eligibility decision.</small></div>}</article><aside className="admission-source-card"><span className="official-source-mark">↗</span><span className="eyebrow">OFFICIAL REFERENCE</span><h3>JAMB IBASS</h3><p>JAMB’s Integrated Brochure and Syllabus System provides a programme eligibility checker and course information. Confirm details there for your chosen institution and year.</p><a className="button button-outline" href="https://ibass.jamb.gov.ng/" target="_blank" rel="noreferrer">Open JAMB IBASS <span>↗</span></a><small>Opens an external official resource · JAMB is not affiliated with TUTOR-ME.</small></aside></div><div className="admission-guidance-strip"><b>Before you apply</b><span>Course name</span><span>Institution</span><span>UTME subject combination</span><span>O’Level requirements</span><span>Admission year</span></div></section>;
}

function ScholarshipDirectory() {
  const [type, setType] = useState("All opportunities");
  const [reminded, setReminded] = useState(false);
  return <section className="resource-workspace"><div className="resource-page-heading"><div><span className="eyebrow">STUDENT OPPORTUNITIES</span><h2>Find support, and check it with the provider.</h2><p>Scholarship availability and deadlines change. We’ll only list opportunities once their provider and application details are verified.</p></div><span className="local-badge">DIRECTORY PREVIEW · NO UNVERIFIED LISTINGS</span></div><div className="scholarship-filters"><label htmlFor="opportunity-type">Browse opportunities<select id="opportunity-type" value={type} onChange={(event) => setType(event.target.value)}><option>All opportunities</option><option>Undergraduate</option><option>Secondary school</option><option>Competitions</option><option>Study support</option></select></label><span>{type} · checked listings</span></div><div className="resource-empty scholarship-empty"><span>✦</span><h3>We’re checking the provider details.</h3><p>There are no verified {type.toLowerCase()} listings in this preview. We won’t make up scholarship names, eligibility rules or deadlines.</p><div className="scholarship-checklist"><b>When you find an opportunity, check:</b><span>✓ &nbsp;The provider’s official website and contact details</span><span>✓ &nbsp;Who can apply and which documents are needed</span><span>✓ &nbsp;The current closing date and whether an application fee applies</span></div><button type="button" className="button button-outline" onClick={() => setReminded(!reminded)}>{reminded ? "Interest noted in this preview ✓" : "Remind me about new listings"}</button>{reminded && <small className="resource-reminder-note">This demo keeps the note on screen only. Notifications need a connected account.</small>}</div></section>;
}
