import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { exams, destinationContent } from "@/lib/content";
import { SectionHeading, ExamCard, ProgressBar, CTA, DestinationCard } from "@/components/ui";
import { InteractivePractice } from "@/components/interactive-practice";
import { AuthDemoForm } from "@/components/auth-demo-form";
import { CbtDemo } from "@/components/cbt-demo";
import { StudentOnboarding } from "@/components/student-onboarding";
import { StudentWorkspace, type WorkspaceMode } from "@/components/student-workspace";
import { ResourcesDirectory } from "@/components/resources-directory";
import { siteUrl } from "@/lib/site";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

const routeSlugs = Object.keys(destinationContent);
const workspaceModes = new Set(["dashboard", "learn", "practice", "ai-tutor", "mistake-bank", "progress", "planner"]);

export function generateStaticParams() {
  return [...routeSlugs, ...exams.map((exam) => exam.slug)].map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  if (workspaceModes.has(slug) || slug === "signin" || slug === "signup") return { title: destinationContent[slug]?.title, robots: { index: false, follow: false } };
  const exam = exams.find((item) => item.slug === slug);
  const page = destinationContent[slug];
  if (exam) return { title: `${exam.name} exam preparation`, description: `${exam.description} Explore subjects, syllabus-led learning, practice and CBT preparation for ${exam.fullName}.`, alternates: { canonical: `${siteUrl}/${slug}` }, openGraph: { title: `${exam.name} preparation | TUTOR-ME`, description: exam.description, url: `${siteUrl}/${slug}`, type: "website" } };
  if (page) return { title: page.title, description: page.intro, alternates: { canonical: `${siteUrl}/${slug}` }, openGraph: { title: `${page.title} | TUTOR-ME`, description: page.intro, url: `${siteUrl}/${slug}`, type: "website" } };
  return {};
}

export default async function DestinationPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ onboarding?: string }> }) {
  const { slug } = await params;
  const query = await searchParams;
  const exam = exams.find((item) => item.slug === slug);
  const page = destinationContent[slug];
  if (!exam && !page) notFound();

  if (workspaceModes.has(slug)) {
    let user = null;
    try { const supabase = await createClient(); user = (await supabase.auth.getUser()).data.user; } catch { /* Configured auth is required below. */ }
    if (!user) redirect(`/signin?next=/${slug}`);
  }

  if (exam) return <main id="main-content" className="destination-page exam-destination">
    <div className={`destination-hero exam-dest-${exam.color}`}><div className="destination-hero-inner"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/exams">Exams</Link><span>/</span><b>{exam.name}</b></div><div className="destination-hero-copy"><span className="eyebrow">{exam.name} preparation · {exam.students}</span><h1>Prepare for {exam.name}<br /><em>with a plan that fits.</em></h1><p>{exam.description}</p><div className="destination-actions"><Link href="/signup" className="button">Build my study plan <span>↗</span></Link><Link href="/practice" className="button button-outline">Try a practice question <span>→</span></Link></div><div className="exam-facts"><span><b>◷</b>{exam.window}</span><span><b>⌁</b>{exam.subjects.length} core subjects to explore</span><span><b>✓</b>Independent preparation</span></div></div><div className="exam-destination-art"><div className="exam-art-orbit" /><span className="exam-art-glyph">{exam.name.slice(0, 1)}</span><div className="exam-art-card"><span>YOUR EXAM GOAL</span><strong>{exam.name}</strong><small>Study a little. Improve a lot.</small><div><i /><i /><i /><i /><i /><i /></div></div><span className="exam-art-note">Clear steps.<br />Confident progress.</span></div></div></div>
    <section className="section destination-subjects"><div className="section-top-row"><SectionHeading eyebrow="Start with your subjects" title="Choose what you’re studying." copy="Explore a subject to see its syllabus, lessons and practice topics. Subject details can be personalised when you create an account." /><span className="subject-count">{exam.subjects.length} SUBJECTS</span></div><div className="subject-grid">{exam.subjects.map((subject, index) => <Link href="/learn" key={subject} className="subject-card"><span className="subject-number">0{index + 1}</span><div className={`subject-art subject-art-${index % 4}`}><span>{["∑", "⚗", "◉", "Aa", "∿", "⌂"][index % 6]}</span></div><strong>{subject}</strong><small>View topics <b>↗</b></small></Link>)}</div></section>
    <section className="exam-plan-band"><div><span className="eyebrow eyebrow-light">Your preparation, organised</span><h2>Learn the topic.<br />Practise what you know.<br /><em>See how you’re improving.</em></h2><p>Follow the syllabus, work through useful practice and use clear explanations to understand each answer.</p><Link className="button button-white" href="/learn">Explore the syllabus <span>↗</span></Link></div><div className="syllabus-card"><div className="syllabus-card-top"><span>SAMPLE STUDY PATH</span><span className="syllabus-chip">{exam.name}</span></div><h3>Biology</h3><p>Demonstration topic grouping · Verify the current syllabus with the exam body.</p><ProgressBar value={64} label="Sample topic progress" color="green" /><div className="syllabus-topic"><span className="topic-done">✓</span><span><strong>Cell structure and organisation</strong><small>Sample lesson · original practice</small></span><b>100%</b></div><div className="syllabus-topic"><span className="topic-active">2</span><span><strong>Nutrition in plants</strong><small>Sample lesson · continue in your library</small></span><b>60%</b></div><div className="syllabus-topic"><span className="topic-upcoming">3</span><span><strong>Transport systems</strong><small>Lesson · Notes · Practice architecture</small></span><b>START</b></div></div></section>
    <section className="section exam-resources"><SectionHeading eyebrow="A complete study space" title="Everything you need to keep moving." copy={`Explore ${exam.name} study tools, all in one place.`} align="center"/><div className="feature-grid"><DestinationCard icon="↗" title="Syllabus and lessons" copy="See what you need to know, then learn each topic step by step." href="/learn"/><DestinationCard icon="⌁" title="Subject practice" copy="Try focused questions and understand the reasoning behind each answer." href="/practice"/><DestinationCard icon="▣" title="CBT experience" copy="Practise with a timer, navigate questions and review your answers." href="/cbt"/><DestinationCard icon="◷" title="Track your progress" copy="See your study rhythm, subject practice and topics to revisit." href="/progress"/></div></section>
    <section className="section exam-demo"><div><SectionHeading eyebrow="A sample from your study session" title="Practise. Check. Understand." copy="Try an original sample question to see how question review works. It is a demonstration, not official past-question content."/><Link className="text-link" href="/practice">Build a practice set <span>↗</span></Link></div><InteractivePractice/></section>
    <section className="section exam-countdown"><div className="countdown-icon">◷</div><div><span className="eyebrow">Your timeline</span><h2>Make a little progress each week.</h2><p>Exam dates can change. Check the examination body&apos;s official updates for confirmed schedules, then shape your study plan around your date.</p></div><Link className="button button-outline" href="/planner">Set my exam date <span>↗</span></Link></section>
    <section className="section more-exams"><div className="section-top-row"><SectionHeading eyebrow="Explore other pathways" title="Preparing for another exam?"/><Link className="quiet-link" href="/exams">All exam destinations ↗</Link></div><div className="exam-grid">{exams.filter((item) => item.slug !== exam.slug).map((item) => <ExamCard key={item.slug} exam={item}/>)}</div></section><CTA title={`Start your ${exam.name} preparation with one clear next step.`} copy="Choose your subjects, set a goal and make a plan that works for you." button="Plan my preparation" />
  </main>;

  return <main id="main-content" className="destination-page"><section className="destination-hero generic-destination"><div className="destination-hero-inner"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><b>{page!.eyebrow}</b></div><div className="generic-hero-grid"><div className="destination-hero-copy"><span className="eyebrow">{page!.eyebrow}</span><h1>{page!.title}</h1><p>{page!.intro}</p><div className="destination-actions"><Link href={slug === "signin" ? "/dashboard" : slug === "signup" ? "/exams" : "/practice"} className="button">{slug === "signin" ? "Continue to dashboard" : slug === "signup" ? "Choose my exam" : "Get started"} <span>↗</span></Link>{slug !== "signup" && slug !== "signin" && <Link href="/exams" className="button button-outline">Explore exams <span>→</span></Link>}</div><div className="page-feature-list">{page!.features.map((feature) => <span key={feature}><b>✓</b>{feature}</span>)}</div></div><div className="generic-hero-art"><div className="generic-art-orbit" /><span>{page!.icon}</span><div className="generic-art-caption"><b>YOUR STUDY SPACE</b><small>A clearer next step, every day.</small></div></div></div></div></section>
    {slug === "signup" ? <section className="section auth-section">{query.onboarding === "1" ? <StudentOnboarding/> : <div className="auth-card"><div className="auth-card-header"><span className="auth-card-icon">✦</span><div><h2>Create your TUTOR-ME account</h2><p>Start a study plan that stays with you.</p></div></div><AuthDemoForm signup/><p className="auth-switch">Already have an account? <Link href="/signin">Sign in</Link></p></div>}<aside className="auth-side-note"><span>✦</span><strong>A thoughtful study routine starts with one good step.</strong><small>Choose your exam, set a goal and keep your learning in one place.</small></aside></section> : slug === "signin" ? <section className="section auth-section"><div className="auth-card"><div className="auth-card-header"><span className="auth-card-icon">{page!.icon}</span><div><h2>Sign in to TUTOR-ME</h2><p>Your study plan is waiting for you.</p></div></div><AuthDemoForm signup={false}/><p className="auth-switch">New to TUTOR-ME? <Link href="/signup">Create your account</Link></p></div><div className="auth-side-note"><span>✦</span><strong>A thoughtful study routine starts with one good step.</strong><small>Choose your exam, set a goal and keep your learning in one place.</small></div></section> : workspaceModes.has(slug) ? <section className="section workspace-shell"><StudentWorkspace mode={slug as WorkspaceMode}/></section> : <>
      <section className="section destination-overview"><div><SectionHeading eyebrow="A clearer way forward" title="Build confidence one step at a time." copy="Your study space helps you turn a big goal into manageable learning sessions."/><div className="overview-chips"><span>✓ &nbsp;Made around your exam</span><span>✓ &nbsp;Progress you can understand</span><span>✓ &nbsp;A steady routine</span></div></div><div className="overview-stat-card"><span className="overview-label">YOUR STUDY RHYTHM</span><div className="overview-stat"><strong>68<span>%</span></strong><span>weekly goal<br/>in progress</span></div><ProgressBar value={68} color="green"/><div className="overview-mini"><span><b>12 days</b><small>Study streak</small></span><span><b>4 subjects</b><small>In your plan</small></span><span><b>320</b><small>JAMB target</small></span></div></div></section>
      {slug === "exams" ? <section className="section exam-directory-section"><div className="section-top-row"><SectionHeading eyebrow="Choose your preparation path" title="Find the exam you’re working towards." copy="Each destination brings subjects, syllabus learning, practice and CBT preparation together."/><span className="demo-label">INDEPENDENT EXAM PREPARATION</span></div><div className="exam-grid">{exams.map((item) => <ExamCard key={item.slug} exam={item}/>)}</div><div className="exam-directory-next"><span>Not sure where to begin?</span><Link href="/signup">Set up your student plan ↗</Link></div></section> : <section className="section destination-tools"><div className="section-top-row"><SectionHeading eyebrow="Explore your study space" title="Useful tools for your next step." copy="Choose a starting point and make the most of your study time."/><span className="demo-label">SAMPLE STUDENT VIEW</span></div><div className="destination-feature-grid">{page!.features.map((feature, index) => <DestinationCard key={feature} icon={["↗", "⌁", "◉"][index % 3]} title={feature} copy={["Work through clear topics and lessons, at a pace that suits you.", "See useful feedback and understand what to revisit next.", "Keep your exam goal in focus as you prepare."][index % 3]} href={["/learn", "/practice", "/planner"][index % 3]}/>)}</div></section>}
      {slug === "cbt" ? <section className="section cbt-page-section"><div className="cbt-page-intro"><SectionHeading eyebrow="Get ready for exam day" title="Practise the CBT experience, at your pace." copy="Choose an answer, move between questions and review before you submit. This short original demo runs in your browser and does not save results."/><div className="cbt-feature-list"><span>◷ &nbsp;20-minute demo timer</span><span>▦ &nbsp;Question navigation</span><span>↻ &nbsp;Answer review</span></div></div><CbtDemo/></section> : slug === "practice" && <section className="section destination-practice"><div><SectionHeading eyebrow="Try a sample question" title="Practice helps learning stick." copy="This original example shows answer selection and review. Question sets will connect to a question service."/><div className="cbt-feature-list"><span>⌁ &nbsp;Topic practice</span><span>◉ &nbsp;Weak topics</span><span>↻ &nbsp;Mistake review</span></div></div><InteractivePractice/></section>}
      {(slug === "news" || slug === "admission" || slug === "scholarships") && <section className="section resource-shell"><ResourcesDirectory mode={slug}/></section>}
      <section className="section next-step-cards"><div className="next-step-card"><span className="next-step-icon">✳</span><span><b>Small steps add up</b><small>Choose one useful activity for today.</small></span><Link href="/planner" aria-label="Open your study planner">↗</Link></div><div className="next-step-card"><span className="next-step-icon green-icon">⌁</span><span><b>Learn, then practise</b><small>Build your confidence topic by topic.</small></span><Link href="/learn" aria-label="Explore lessons">↗</Link></div><div className="next-step-card"><span className="next-step-icon gold-icon">◷</span><span><b>Keep your progress visible</b><small>See the work you’ve put in.</small></span><Link href="/progress" aria-label="View progress">↗</Link></div></section>
    </>}
    <CTA title="A better study routine can start today." copy="Choose your exam and find the next step that feels right." />
  </main>;
}
